name: Deploy Refugio to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Entrar a la carpeta
            cd ~/refugio-animales
            
            # 2. Descargar últimos cambios
            git pull origin main
            
            # 3. Reconstruir y levantar (La opción --build fuerza a instalar librerías nuevas)
            docker compose up -d --build --remove-orphans
            
            # 4. Esperar unos segundos a que la base de datos arranque (por seguridad)
            sleep 10
            
            # 5. Aplicar cambios en la base de datos (Migraciones) AUTOMÁTICAMENTE
            # El flag -T es vital para que funcione en modo automático (sin terminal interactiva)
            docker compose exec -T backend python manage.py migrate --noinput
            
            # 6. Recopilar estilos (CSS) para que el panel se vea bonito AUTOMÁTICAMENTE
            docker compose exec -T backend python manage.py collectstatic --noinput
            
            # 7. Limpiar basura vieja para ahorrar espacio
            docker image prune -f